spring.application.name=college-complaint-request-management
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/college_complaints

spring.thymeleaf.cache=false

app.seed.admin-id=admin
app.seed.admin-password=admin123
app.seed.user-id=student
app.seed.user-password=student123
